// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListAPI.Models;

#nullable disable

namespace ToDoListAPI.Migrations
{
    [DbContext(typeof(ListDB))]
    [Migration("20231223180720_userIdAdded")]
    partial class userIdAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoListAPI.Models.task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Finished = false,
                            TaskDescription = "read at lest 1 book this month",
                            TaskName = "read books",
                            UserId = "6f6aba9d - 9696 - 46d1 - a0ac - 26aaecebcc17"
                        },
                        new
                        {
                            TaskId = 2,
                            Finished = true,
                            TaskDescription = "clean your bedroom",
                            TaskName = "clean room",
                            UserId = "6f6aba9d - 9696 - 46d1 - a0ac - 26aaecebcc17"
                        },
                        new
                        {
                            TaskId = 3,
                            Finished = false,
                            TaskDescription = "organize your laptop desktop",
                            TaskName = "organize",
                            UserId = "6f6aba9d - 9696 - 46d1 - a0ac - 26aaecebcc17"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
